### ISSUE TITLE
functional-fortran as an fpm package

### ISSUE THREAD

**Issue by dnaviap** [wavebitscientific/functional-fortran#17]
Hello Milan, a lot of thanks for all your contributions. I think it must be very useful to have the functional-fortran as an fpm package.

**Comment by awvwgk** [comment]
For fpm support the following fpm.toml should be sufficient (w/o tests):

```toml
name = "functional-fortran"
version = "0.5.0"
license = "BSD-3-Clause"

[library]
source-dir = "src/lib"
```
